import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './views/header/index'
import NavBar from './views/navbar/index'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-black text-white'>
      <body className={inter.className}>
        <div className='bg-black text-white'>
        <Header/>
        <div className='flex'>
        <NavBar/>
        {children}
        </div>
        </div>
      
       </body>
    </html>
  )
}
